image: greenjune/vtk2023

tasks:

    - name: install mamba 
      command: |
          wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
          bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/mambaforge && rm Mambaforge-$(uname)-$(uname -m).sh
          source ${HOME}/.bashrc
          ../mambaforge/bin/mamba init bash
          python -m http.server 8000
    #- name: Install Nextflow & nf core
      #command: |
          #curl -s https://get.nextflow.io | bash
          #sudo mv nextflow /bin/
          #export PATH=/bin:$PATH
    
    #- name: Install Nextflow & nf core
      #command: |
          
          #pip install nf-core
    #- name: retrieve ena data
      #command: |
          #cd bostrom/
          #wget http://ftp.ebi.ac.uk/pub/databases/ena/tools/ena-file-downloader.zip
          #unzip -d ena ena-file-downloader.zip
          #while read i;do java -jar ena/ena-file-downloader.jar --accessions=$i --format=READS_FASTQ --location=../ --protocol=FTP --asperaLocation=null;done < ids.csv
          #rm -rf ena/ ena ena-file-downloader.zip
          #cd ../
    #- name: retrieve references data
      #command: |
          #cd bostrom/
          #curl -L -o ref.tar.gz https://cloud.uni-konstanz.de/index.php/s/oRNt35g4sCJmttr/download
          #tar -xf ref.tar.gz
          #rm -rf ref.tar.gz
          #cd ../
          
#ports:
    #- port: 8000
      #onOpen: open-preview   


vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore # Language support for .gitignore files
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - REditorSupport.r
    - quarto.quarto
